"""
Django settings for db_downloader project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fo+()x+x(+1_$i_xslsjxx6n&##w9!ua^egzk0_6da(7kqpldm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.22.43.125', '172.22.43.180', '172.24.3.186', 's460-aud06', 'localhost', 's460-aud04']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'data_managment.apps.DataManagmentConfig',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'db_downloader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '..\\templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'db_downloader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'USER' : 'root',
        'PASSWORD' : '',
        'NAME' : 'db_downloader_prod',
        'PORT': '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

DEBUG = True

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '..\\assets'),
)

#Custom system configuration
LOCAL_DB_CONNECTION = {
    'CONNECTION_TYPE'   :'NATIVE',
    'DSN'               :'TABLES_DOWNLOAD_CON',
    'HOST'              :'localhost',
    'DB_TYPE'           :'MariaDb',
    'USER'              :'root',
    'DB'                :'audit_data_mining',
    'PASSWORD'          :'toor',
    'PORT'              : 3307
}

DB_DRIVERS_FOR_CONNECTION = {
    'MYSQL'     :'MySQL ODBC 5.1 Driver',
    'SQLSERVER' :'ODBC Driver 13 for SQL Server',
    'ORACLE'    :'Oracle ODBC 5.1 Driver'    
}

NUMBER_OF_PARALLEL_DOWNLOADS = 10
MAXIMUM_FECTH_DOWNLOAD = 10000
DOWNLOAD_FIXED_TOKEN = '3iWt0nB4Xo01KS88Cfjqg2V31XUPRxWH'

DB_SOPORTED_DATE = ['DATE', 'DATETIME']
DB_SOPORTED_FLOAT = ['FLOAT', 'DECIMAL', 'DOUBLE', 'REAL']

NOT_RUN_ON_DAYS = [3]