# Generated by Django 2.1.1 on 2019-07-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=20, null=True)),
                ('dsn', models.CharField(max_length=100, null=True)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('error_description', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.Connection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('schedule', models.TextField(max_length=400000)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_date', models.DateTimeField(null=True)),
                ('last_run_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Calendario de Descarga',
                'verbose_name_plural': 'Calendarios de Descargas',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_tables', to='data_managment.DownloadSchedule')),
            ],
            options={
                'verbose_name': 'Tabla Candelarizada',
                'verbose_name_plural': 'Tablas Calendarizadas',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400000)),
                ('download_name', models.CharField(max_length=100)),
                ('schedule', models.TextField(max_length=400000)),
                ('is_updating', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_append', models.BooleanField(default=True)),
                ('last_update_date', models.DateTimeField(null=True)),
                ('last_access_date', models.DateTimeField(null=True)),
                ('next_update_date', models.DateField(null=True)),
                ('download_filter', models.TextField(max_length=2000)),
                ('download_order', models.IntegerField()),
                ('download_script', models.TextField(max_length=400000)),
                ('db_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.DbSchema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=600)),
                ('field_description', models.TextField(max_length=300)),
                ('decimal_precision', models.IntegerField()),
                ('length', models.IntegerField()),
                ('is_indexed', models.BooleanField(default=False)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.DataTypes')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scheduledtables',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_schedules', to='data_managment.Table'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.ConnectionType'),
        ),
        migrations.AddField(
            model_name='connection',
            name='db_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_managment.DbType'),
        ),
    ]
