# Generated by Django 2.1.1 on 2019-07-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dberrorlog',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data_managment.Table'),
        ),
        migrations.AddField(
            model_name='table',
            name='pending_to_download',
            field=models.BooleanField(default=False),
        ),
    ]
