# Generated by Django 2.1.1 on 2019-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_managment', '0002_auto_20190723_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbQueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('query', models.TextField(max_length=400000)),
                ('user', models.TextField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
