# Generated by Django 2.1.1 on 2019-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_managment', '0003_dbquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
