# Generated by Django 2.1.1 on 2019-08-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_managment', '0004_connection_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dynamic_download_filter',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
